/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.renthouseapp;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType RentalRecord.
 *
 * @since 2026-04-12
 */
@PrimaryKeys({"id"})
public final class RentalRecord extends CloudDBZoneObject {
    private String id;

    private String propertyId;

    private String propertyName;

    private String tenantName;

    @NotNull
    @DefaultValue(stringValue = "")
    private String tenantPhone;

    private String tenantIdCard;

    private Date contractDate;

    private Date rentStartDate;

    private Integer monthlyRent;

    private Integer leaseMonths;

    private Integer paymentFrequency;

    @DefaultValue(booleanValue = false)
    private Boolean isCompleted;

    private String createdBy;

    private Date createdAt;

    private String updatedBy;

    private Date updatedAt;

    private Integer depositAmount;

    @DefaultValue(stringValue = "未支付")
    private String depositStatus;

    private Integer propertyFee;

    public RentalRecord() {
        super(RentalRecord.class);
        this.tenantPhone = "";
        this.isCompleted = false;
        this.depositStatus = "未支付";
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId;
    }

    public String getPropertyId() {
        return propertyId;
    }

    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    public String getPropertyName() {
        return propertyName;
    }

    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    public String getTenantName() {
        return tenantName;
    }

    public void setTenantPhone(String tenantPhone) {
        this.tenantPhone = tenantPhone;
    }

    public String getTenantPhone() {
        return tenantPhone;
    }

    public void setTenantIdCard(String tenantIdCard) {
        this.tenantIdCard = tenantIdCard;
    }

    public String getTenantIdCard() {
        return tenantIdCard;
    }

    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    public Date getContractDate() {
        return contractDate;
    }

    public void setRentStartDate(Date rentStartDate) {
        this.rentStartDate = rentStartDate;
    }

    public Date getRentStartDate() {
        return rentStartDate;
    }

    public void setMonthlyRent(Integer monthlyRent) {
        this.monthlyRent = monthlyRent;
    }

    public Integer getMonthlyRent() {
        return monthlyRent;
    }

    public void setLeaseMonths(Integer leaseMonths) {
        this.leaseMonths = leaseMonths;
    }

    public Integer getLeaseMonths() {
        return leaseMonths;
    }

    public void setPaymentFrequency(Integer paymentFrequency) {
        this.paymentFrequency = paymentFrequency;
    }

    public Integer getPaymentFrequency() {
        return paymentFrequency;
    }

    public void setIsCompleted(Boolean isCompleted) {
        this.isCompleted = isCompleted;
    }

    public Boolean getIsCompleted() {
        return isCompleted;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getCreatedAt() {
        return createdAt;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public String getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setDepositAmount(Integer depositAmount) {
        this.depositAmount = depositAmount;
    }

    public Integer getDepositAmount() {
        return depositAmount;
    }

    public void setDepositStatus(String depositStatus) {
        this.depositStatus = depositStatus;
    }

    public String getDepositStatus() {
        return depositStatus;
    }

    public void setPropertyFee(Integer propertyFee) {
        this.propertyFee = propertyFee;
    }

    public Integer getPropertyFee() {
        return propertyFee;
    }

}
