/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.renthouseapp;

import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;
import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;

import java.util.Date;

/**
 * Definition of ObjectType Rental.
 *
 * @since 2026-04-01
 */
@PrimaryKeys({"id"})
public final class Rental extends CloudDBZoneObject {
    private String id;

    private String propertyId;

    private String propertyName;

    private String tenantName;

    @NotNull
    @DefaultValue(stringValue = "")
    private String tenantPhone;

    private String tenantIdCard;

    private Date contractDate;

    private Date rentStartDate;

    private Integer monthlyRent;

    private Integer leaseMonths;

    private Integer paymentFrequency;

    public Rental() {
        super(Rental.class);
        this.tenantPhone = "";
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId;
    }

    public String getPropertyId() {
        return propertyId;
    }

    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    public String getPropertyName() {
        return propertyName;
    }

    public void setTenantName(String tenantName) {
        this.tenantName = tenantName;
    }

    public String getTenantName() {
        return tenantName;
    }

    public void setTenantPhone(String tenantPhone) {
        this.tenantPhone = tenantPhone;
    }

    public String getTenantPhone() {
        return tenantPhone;
    }

    public void setTenantIdCard(String tenantIdCard) {
        this.tenantIdCard = tenantIdCard;
    }

    public String getTenantIdCard() {
        return tenantIdCard;
    }

    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    public Date getContractDate() {
        return contractDate;
    }

    public void setRentStartDate(Date rentStartDate) {
        this.rentStartDate = rentStartDate;
    }

    public Date getRentStartDate() {
        return rentStartDate;
    }

    public void setMonthlyRent(Integer monthlyRent) {
        this.monthlyRent = monthlyRent;
    }

    public Integer getMonthlyRent() {
        return monthlyRent;
    }

    public void setLeaseMonths(Integer leaseMonths) {
        this.leaseMonths = leaseMonths;
    }

    public Integer getLeaseMonths() {
        return leaseMonths;
    }

    public void setPaymentFrequency(Integer paymentFrequency) {
        this.paymentFrequency = paymentFrequency;
    }

    public Integer getPaymentFrequency() {
        return paymentFrequency;
    }

}
